### ISSUE TITLE
🐛 Bug Report:  HTTP call to `Client` throws error due to he `HttpMethod` enum not being exported from `client.dart`

### ISSUE THREAD

**Issue by hanskokx** [appwrite/sdk-generator#699]
### 👟 Reproduction steps

When I attempt to make an HTTP call to the `Client`, I am unable to due to the `HttpMethod` enum not being exported from `client.dart`:

```dart
await client.call(
  HttpMethod.get,
  path: '/',
);
```

### 👍 Expected behavior

I should be able to make a call to the `Client` using the provided `enum`.

### 👎 Actual Behavior

The `HttpMethod` enum is not exported from `client.dart`, therefore I am unable to use the `call` method on the `Client`.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Something else

### 🧱 Your Environment

This is a client issue, not a server issue.

My `pubspec.yaml` specifies `appwrite: ^9.0.1`.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hey @hanskokx , may I know the reason why you are using `client.call` ?

**Comment by hanskokx** [comment]
@joeyouss It's been a couple of weeks since I filed this (and I've since moved on from the project _and_ taken a vacation). I can no longer recall _why_ I was trying to call the client directly. :)

**Comment by joeyouss** [comment]
hI @hanskokx , apologies for the delayed response so the reason why I asked this is basically - client.call is an internal method used by us and not meant for public usage since it won't be working as expected by you. I understand, this might have been a bit confusing and for everything that is usable - our docs are a reference for that https://appwrite.io/docs. Thank you so much for opening the issue and your reply!

**Comment by hanskokx** [comment]
Not a problem! I _think_ the reason was that I wanted to move a file from one bucket to another (e.g., private bucket to public bucket) without downloading/re-uploading the button. I thought maybe I could do it by calling the client directly. If I had a guess, that would be why I filed the bug.

**Comment by joeyouss** [comment]
I totally get it but that won't actually help you do that. A potential solution could be using document-level permissions and changing the permissions on the file itself to public instead of moving it to a bucket with public permissions.

**Comment by hanskokx** [comment]
Fair enough. I was working within my client's constraints, though. This is how they set it up. 🤷🏻‍♂️

**Comment by joeyouss** [comment]
Oh, I understand

**Comment by gewenyu99** [comment]
@hanskokx I just noticed this. This is a fascinating approach, I mean, we don't expose the Client because it's really supposed to be an internal class. If you need to switch between buckets, you'll likely need to do something strange with the buffers.

You CAN do this by just not using the SDK at all and use HTTP directly. You'll probably struggle with the chunk-upload implementation a little for large files. They're just a nightmare for everyone 🥼 I lost many hairs when working without the SDK, but you can peep the generated SDK code and just copy it.

Checkout this page: https://appwrite.io/docs/rest

I really don't think we're going to support this any time soon though, but maybe this can be a community contribution, as a utility extension to the Appwrite SDKs?

Hope this is reasonable to hear ❤️
